### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [chrhauris/tagtomarkdown#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.4.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary tagtomarkdown -w /tmp/ext tagtomarkdown==0.4.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting tagtomarkdown==0.4.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/b41/297c0b4545ffe/tagtomarkdown-0.4.0.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-wc66zlpx/tagtomarkdown/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-wc66zlpx/tagtomarkdown/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-wc66zlpx/tagtomarkdown/pip-egg-info
         cwd: /tmp/pip-wheel-wc66zlpx/tagtomarkdown/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-wc66zlpx/tagtomarkdown/setup.py", line 5, in <module>
        with open('LICENSE.txt') as license_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I can't autofix because there appears to be a dep on building `sample/doc/site/Page1.html`
